# Generated by Django 2.1.3 on 2018-12-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0003_auto_20181225_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='score',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
