# Generated by Django 2.1.2 on 2018-12-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_group_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='study_form',
            field=models.SmallIntegerField(choices=[(0, 'Бакалавриат'), (1, 'Магистратура')], default=0),
            preserve_default=False,
        ),
    ]
