# Generated by Django 2.1.2 on 2018-12-25 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study_group_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerToCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Прием открыт'), (1, 'Прием закрыт')], default=0)),
                ('min_quantity', models.IntegerField(default=15)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Связь курсов по выбору и наборов',
            },
        ),
        migrations.CreateModel(
            name='ContainerToGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Связи групп и наборов на курсы',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='uploads')),
            ],
            options={
                'verbose_name_plural': 'Курсы по выбору',
            },
        ),
        migrations.CreateModel(
            name='CourseContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('status', models.SmallIntegerField(choices=[(0, 'Набор открыт'), (1, 'Набор закрыт')], default=0)),
            ],
            options={
                'verbose_name_plural': 'Наборы курсов',
                'ordering': ['created_at'],
                'get_latest_by': ['crated_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CourseMediaFilesLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(unique=True, upload_to='uploads')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('uploading_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Ссылки на медиа курсов',
                'get_latest_by': 'uploading_date',
            },
        ),
        migrations.CreateModel(
            name='CourseRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Подана'), (1, 'Принята'), (2, 'Отклонена')], default=0)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('active_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='course_module.ContainerToCourse')),
            ],
            options={
                'verbose_name_plural': 'Заявки на курсы по выбору',
            },
        ),
        migrations.CreateModel(
            name='CourseToInstitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_institute_relations', to='course_module.Course')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_course_relations', to='study_group_module.Institute')),
            ],
        ),
    ]
