# Generated by Django 2.1.2 on 2018-12-25 13:06

import course_module.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study_group_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserequest',
            name='student',
            field=models.ForeignKey(limit_choices_to=course_module.models.get_only_students_q, on_delete=django.db.models.deletion.CASCADE, related_name='student_course_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursemediafileslinks',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='course_module.Course'),
        ),
        migrations.AddField(
            model_name='coursehead',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_head_relations', to='course_module.ContainerToCourse'),
        ),
        migrations.AddField(
            model_name='coursehead',
            name='curator',
            field=models.ForeignKey(limit_choices_to=course_module.models.get_only_professors_q, on_delete=models.SET(course_module.models.get_sentinel_user), related_name='professor_course_head_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursecontainer',
            name='courses',
            field=models.ManyToManyField(related_name='course_containers', through='course_module.ContainerToCourse', to='course_module.Course'),
        ),
        migrations.AddField(
            model_name='coursecontainer',
            name='created_by',
            field=models.ForeignKey(limit_choices_to=course_module.models.get_workers_with_unit_creating_permission_q, on_delete=django.db.models.deletion.DO_NOTHING, related_name='containers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursecontainer',
            name='groups',
            field=models.ManyToManyField(related_name='group_containers', through='course_module.ContainerToGroup', to='study_group_module.StudyGroup'),
        ),
        migrations.AddField(
            model_name='course',
            name='containers',
            field=models.ManyToManyField(through='course_module.ContainerToCourse', to='course_module.CourseContainer'),
        ),
        migrations.AddField(
            model_name='course',
            name='institutes',
            field=models.ManyToManyField(related_name='courses', through='course_module.CourseToInstitute', to='study_group_module.Institute'),
        ),
        migrations.AddField(
            model_name='containertogroup',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_group_relations', to='course_module.CourseContainer'),
        ),
        migrations.AddField(
            model_name='containertogroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_relations', to='study_group_module.StudyGroup'),
        ),
        migrations.AddField(
            model_name='containertocourse',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_course_relations', to='course_module.CourseContainer'),
        ),
        migrations.AddField(
            model_name='containertocourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_container_relations', to='course_module.Course'),
        ),
        migrations.AddField(
            model_name='containertocourse',
            name='heads',
            field=models.ManyToManyField(related_name='courses', through='course_module.CourseHead', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='courserequest',
            unique_together={('student', 'active_course')},
        ),
        migrations.AlterUniqueTogether(
            name='coursecontainer',
            unique_together={('name', 'created_at')},
        ),
        migrations.AlterUniqueTogether(
            name='containertogroup',
            unique_together={('group', 'container')},
        ),
        migrations.AlterUniqueTogether(
            name='containertocourse',
            unique_together={('course', 'container')},
        ),
    ]
