# Generated by Django 2.1.2 on 2018-12-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_module', '0003_auto_20181225_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.TextField(blank=True),
        ),
    ]
