# Generated by Django 2.1.3 on 2018-12-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_module', '0004_course_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserequest',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
