# Generated by Django 2.1.2 on 2018-12-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Чаты пользователей',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Сообщения пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserMediaFilesLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(unique=True, upload_to='uploads')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('uploading_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Ссылки на медиа курсов',
                'get_latest_by': 'uploading_date',
            },
        ),
    ]
